# Generated by Django 4.2.7 on 2023-12-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_perfil',
            name='apellidos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_perfil',
            name='cedula',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_perfil',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user_perfil',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_perfil',
            name='nombres',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
